### PR TITLE
Install golangci-lint into images about go

### PR DESCRIPTION
**Pull request by jumpeiMano**
I Added commands to install [`golangci-lint`](https://github.com/golangci/golangci-lint) into images include golang image.

### CODE REVIEW

**Comment by aibou** [comment]
Thanks!

I don't enough understand about `golangci-lint`, so could you tell me `golangci-lint` is not need to run the command like `gometalinter --install`?

**Comment by jumpeiMano** [comment]
There is no need to execute commands other than `go get -u github.com / golangci / golangci-lint / cmd / golangci-lint`.
I built and run this way in my local environment and confirmed that it works without problems.

ref: https://github.com/golangci/golangci-lint#windows-macos-and-linux

**Comment by aibou** [comment]
Awesome!
Thank you for your kindness. LGTM

**Comment by jumpeiMano** [comment]
Thanks!

**Pull request merged**
